// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2y9z9dntcGdPGTmcpqz36RyX8ZXUo8E',
    appId: '1:217641499247:web:4659223b91f9d20a246b9a',
    messagingSenderId: '217641499247',
    projectId: 'ecommerceaapp-5e165',
    authDomain: 'ecommerceaapp-5e165.firebaseapp.com',
    storageBucket: 'ecommerceaapp-5e165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Ra5gdNeOaYDcwDa3tHnVRVnoD4uFUxY',
    appId: '1:217641499247:android:5dfce7a6b7e41b55246b9a',
    messagingSenderId: '217641499247',
    projectId: 'ecommerceaapp-5e165',
    storageBucket: 'ecommerceaapp-5e165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2SQ96njjjt2VkVx0nRweTWkkfaJOQGF8',
    appId: '1:217641499247:ios:682acfe540e8f996246b9a',
    messagingSenderId: '217641499247',
    projectId: 'ecommerceaapp-5e165',
    storageBucket: 'ecommerceaapp-5e165.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2SQ96njjjt2VkVx0nRweTWkkfaJOQGF8',
    appId: '1:217641499247:ios:682acfe540e8f996246b9a',
    messagingSenderId: '217641499247',
    projectId: 'ecommerceaapp-5e165',
    storageBucket: 'ecommerceaapp-5e165.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2y9z9dntcGdPGTmcpqz36RyX8ZXUo8E',
    appId: '1:217641499247:web:3677000f50fc27b0246b9a',
    messagingSenderId: '217641499247',
    projectId: 'ecommerceaapp-5e165',
    authDomain: 'ecommerceaapp-5e165.firebaseapp.com',
    storageBucket: 'ecommerceaapp-5e165.firebasestorage.app',
  );
}
